import { Product } from "@/app/store/objects/product";

export const listProducts = async (): Promise<Product[]> => [
  {
    id: "coffee-beans-1",
    title: "Premium Coffee Beans",
    description:
      "Sourced from the finest coffee plantations, these premium coffee beans are carefully roasted to perfection. Perfect for your morning brew.",
    category: "Beverages",
    condition: "new",
    brand: "Artisan Roasters",
    tags: ["coffee", "beans", "premium", "organic"],
    fulfillmentType: "shipping",
    options: [
      {
        id: "pack-size-option",
        name: "Pack Size",
        values: ["250g", "500g", "1kg"],
        position: 1,
      },
    ],
    defaultVariantId: "coffee-beans-500g",
    variants: [
      {
        id: "coffee-beans-250g",
        title: "250g",
        sku: "CB-250",
        price: 12.99,
        compareAtPrice: 15.99,
        currency: "USD",
        weight: { amount: 250, unit: "g" },
        currentlyNotInStock: false,
        availableForSale: true,
        selectedOptions: [{ name: "Pack Size", value: "250g" }],
        image: {
          id: "coffee-beans-250g-img",
          url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
          altText: "Coffee beans package 250g",
          width: 400,
          height: 400,
        },
        quantityAvailable: 50,
        taxable: true,
      },
      {
        id: "coffee-beans-500g",
        title: "500g",
        sku: "CB-500",
        price: 22.99,
        compareAtPrice: 28.99,
        currency: "USD",
        weight: { amount: 500, unit: "g" },
        currentlyNotInStock: false,
        availableForSale: true,
        selectedOptions: [{ name: "Pack Size", value: "500g" }],
        image: {
          id: "coffee-beans-500g-img",
          url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
          altText: "Coffee beans package 500g",
          width: 400,
          height: 400,
        },
        quantityAvailable: 30,
        taxable: true,
      },
      {
        id: "coffee-beans-1kg",
        title: "1kg",
        sku: "CB-1000",
        price: 39.99,
        compareAtPrice: 49.99,
        currency: "USD",
        weight: { amount: 1, unit: "kg" },
        currentlyNotInStock: false,
        availableForSale: false,
        selectedOptions: [{ name: "Pack Size", value: "1kg" }],
        image: {
          id: "coffee-beans-1kg-img",
          url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400",
          altText: "Coffee beans package 1kg",
          width: 400,
          height: 400,
        },
        quantityAvailable: 0,
        taxable: true,
      },
    ],
    currency: "USD",
    priceRange: {
      minVariantPrice: 12.99,
      maxVariantPrice: 39.99,
    },
    compareAtPriceRange: {
      minVariantPrice: 15.99,
      maxVariantPrice: 49.99,
    },
    featuredImage: {
      id: "coffee-beans-featured-img",
      url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800",
      altText: "Premium Coffee Beans",
      width: 800,
      height: 800,
    },
    media: [
      {
        type: "image",
        previewImage: {
          id: "coffee-beans-media-img",
          url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800",
          altText: "Premium Coffee Beans",
          width: 800,
          height: 800,
        },
        presentation: "image",
      },
    ],
    totalInventory: 80,
  },
  {
    id: "v60-filters",
    title: "V60 Filters",
    description:
      "V60 filters are a type of coffee filter that is used to brew coffee in a V60 cone. They are made of paper and are designed to fit in a V60 cone.",
    category: "Beverages",
    condition: "new",
    brand: "Hario",
    tags: ["coffee", "filters", "v60"],
    fulfillmentType: "shipping",
    options: [
      {
        id: "pack-size-option",
        name: "Pack Size",
        values: ["100 pcs", "250 pcs", "500 pcs"],
        position: 1,
      },
    ],
    defaultVariantId: "v60-filters-500pcs",
    variants: [
      {
        id: "v60-filters-100pcs",
        title: "100 pcs",
        sku: "VF-100",
        price: 4.99,
        compareAtPrice: 6.99,
        currency: "USD",
        weight: { amount: 50, unit: "g" },
        currentlyNotInStock: false,
        availableForSale: true,
        selectedOptions: [{ name: "Pack Size", value: "100 pcs" }],
        image: {
          id: "v60-filters-100pcs-img",
          url: "https://images.unsplash.com/photo-1521677446241-d182a96ec49f?w=400",
          altText: "V60 filters package 100 pcs",
          width: 400,
          height: 400,
        },
        quantityAvailable: 5,
        taxable: true,
      },
      {
        id: "v60-filters-250pcs",
        title: "250 pcs",
        sku: "VF-250",
        price: 9.99,
        compareAtPrice: 12.99,
        currency: "USD",
        weight: { amount: 125, unit: "g" },
        currentlyNotInStock: false,
        availableForSale: true,
        selectedOptions: [{ name: "Pack Size", value: "250 pcs" }],
        image: {
          id: "v60-filters-250pcs-img",
          url: "https://images.unsplash.com/photo-1521677446241-d182a96ec49f?w=400",
          altText: "V60 filters package 250 pcs",
          width: 400,
          height: 400,
        },
        quantityAvailable: 50,
        taxable: true,
      },
      {
        id: "v60-filters-500pcs",
        title: "500 pcs",
        sku: "VF-500",
        price: 14.99,
        compareAtPrice: 19.99,
        currency: "USD",
        weight: { amount: 200, unit: "g" },
        currentlyNotInStock: false,
        availableForSale: false,
        selectedOptions: [{ name: "Pack Size", value: "500 pcs" }],
        image: {
          id: "v60-filters-500pcs-img",
          url: "https://images.unsplash.com/photo-1521677446241-d182a96ec49f?w=400",
          altText: "V60 filters package 500 pcs",
          width: 400,
          height: 400,
        },
        quantityAvailable: 0,
        taxable: true,
      },
    ],
    currency: "USD",
    priceRange: {
      minVariantPrice: 4.99,
      maxVariantPrice: 14.99,
    },
    compareAtPriceRange: {
      minVariantPrice: 6.99,
      maxVariantPrice: 19.99,
    },
    featuredImage: {
      id: "v60-filters-featured-img",
      url: "https://images.unsplash.com/photo-1521677446241-d182a96ec49f?w=800",
      altText: "V60 Filters",
      width: 800,
      height: 800,
    },
    media: [
      {
        type: "image",
        previewImage: {
          id: "v60-filters-media-img",
          url: "https://images.unsplash.com/photo-1521677446241-d182a96ec49f?w=800",
          altText: "V60 Filters",
          width: 800,
          height: 800,
        },
        presentation: "image",
      },
    ],
    totalInventory: 55,
  },
];
